version: 0.2

env:
  variables:
    DEBUG: "0"
    CC: "gcc-4.9"
    CXX: "g++-4.9"
    ARCH: "64"        
phases:
  install:
    commands:
      - sudo apt-get -y -q update 
      - sudo apt-get -y -q upgrade
      - sudo apt-get -y -q install software-properties-common
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - sudo apt-get -y -q update
      - sudo apt-get -y -q upgrade
      - sudo apt-get -y -q install gcc-4.9 g++-4.9
      - sudo apt-get -y -q install zlib1g-dev libsdl1.2-dev libjpeg-dev nasm tar libbz2-dev libgtk2.0-dev cmake mercurial libfluidsynth-dev libgl1-mesa-dev libssl-dev libglew-dev 
  pre_build:
    commands:
      - mkdir buildclient
      - mkdir buildserver
      - wget -nc http://zandronum.com/essentials/fmod/fmodapi42416linux"$ARCH".tar.gz 
      - tar -xvzf fmodapi42416linux"$ARCH".tar.gz
  build:
    commands:
      - cd buildclient
      - cmake -DCMAKE_BUILD_TYPE=Release -DFMOD_LIBRARY=`pwd`/../fmodapi42416linux"$ARCH"/api/lib/libfmodex"$ARCH"-4.24.16.so -DFMOD_INCLUDE_DIR=`pwd`/../fmodapi42416linux"$ARCH"/api/inc .. 
      - make
      - make clean
      - cd ../buildserver
      - cmake -DCMAKE_BUILD_TYPE=Release -DSERVERONLY=ON ..
      - make
  post_build:
    commands: 
      - cd ..
      - ls -l buildclient/
      - ls -l buildserver/ 
artifacts:
  files:
    - 'buildclient/*'
    - 'buildserver/*'
